services:
  apache:
    build: .
    image: php:8.0-apache
    container_name: apache_container
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html  # Your local ./backend folder is mounted here
    networks:
      - lamp_network
    env_file:
      - .env

  mysql:
    image: mariadb:latest
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - lamp_network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin_container
    restart: always

    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
    - "8081:80"
    networks:
      - lamp_network

networks:
  lamp_network:
    driver: bridge
